# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/android-starter-template
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
        name: "Setup custom environment variables"
        command: |
          echo 'FABRIC_API_KEY='$FABRIC_API_KEY >> app/build.properties
    - run:
        name: Who am I
        command: whoami
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Common Module Unit Tests
        command: ./gradlew :common:test
    - store_artifacts:
        path: common/build/reports
    - store_test_results:
        path: common/build/test-results
    - run:
        name: Run Presentation Module Unit Tests
        command: ./gradlew :presentation:test
    - store_artifacts:
        path: presentation/build/reports
    - store_test_results:
        path: presentation/build/test-results
    - run:
        name: Run Domain Module Unit Tests
        command: ./gradlew :domain:test
    - store_artifacts:
        path: domain/build/reports
    - store_test_results:
        path: domain/build/test-results
    - run:
        name: Run Data Module Unit Tests
        command: ./gradlew :data:testDebugUnitTest
    - store_artifacts:
        path: data/build/reports
    - store_test_results:
        path: data/build/test-results
    - run:
          name: Jacoco Test Coverage
          command: ./gradlew jacocoTestReport
    - store_artifacts:
          path: app/build/reports/jacoco
    - run:
          name: Run Check
          command: ./gradlew check
    - store_artifacts:
          path: app/build/reports
    - codecov/upload:
        file: app/build/reports/
