# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/android-starter-template
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
        name: "Setup custom environment variables"
        command: |
          echo 'FABRIC_API_KEY='$FABRIC_API_KEY >> app/build.properties
    - run:
        name: Who am I
        command: whoami
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run App Module Build
        command: ./gradlew build jacocoTestReport
    - store_artifacts:
        path: app/build/reports
    - codecov/upload:
        file: app/build/reports/coverage/*.html
    - run:
        name: Run Common Module Build
        command: ./gradlew :common:build
    - store_artifacts:
        path: common/build/reports
    - store_test_results:
        path: common/build/test-results
    - run:
        name: Run Presentation Module Build
        command: ./gradlew :presentation:build
    - store_artifacts:
        path: presentation/build/reports
    - store_test_results:
        path: presentation/build/test-results
    - run:
        name: Run Domain Module Build
        command: ./gradlew :domain:build
    - store_artifacts:
        path: domain/build/reports
    - store_test_results:
        path: domain/build/test-results
    - run:
        name: Run Data Module Build
        command: ./gradlew :data:build
    - store_artifacts:
        path: data/build/reports
    - store_test_results:
        path: data/build/test-results
